# 주피터 노트북

## 셀 타입

- 코드
- 마크다운/텍스트
- Ctrl + m, m (코드셀 -> 마크다운셀)
- Ctrl + m, y (마크다운셀 -> 코드셀)
- Ctrl + m, d (셀삭제)

## 셀 모드

- 편집(edit mode)
- 명령(command mode)


## 셀 실행

- Shift + Enter 현재 셀 실행하고 아래 셀 선택
- Ctrl + Enter 현재 셀 실행하고 현재 셀 선택
- Alt + Enter (colab) 현재 셀 실행하고 아래에 새로운 코드 셀 생성

## 단축키
- 구글 코랩에서는 노트북 단축키를 사용자가 지정할 수 있으며, 일반적인 주피터노트북과 달리 셀 편집모드에서도 단축키를 통해 셀 잘라내기, 새로운 셀 생성 등 셀 편집이 가능

- '메뉴-도구-단축키'에서 설정
    - 셀 잘라내기 Ctrl + m, x
    - 셀 복사하기 Ctrl + m, c
    - 셀 붙이기 Ctrl + v
    - 셀 삭제 Ctrl + m, d
    - 위에 새로운 셀 삽입하기 Ctrl + m, a
    - 아래에 새로운 셀 삽입하기 Ctrl + m, b
    - 셀 타입 코드로 변환 Ctrl + m, y
    - 셀 타입 마크다운으로 변환 Ctrl + m, m
    - 실행 취소 Ctrl + m, z
    - 단축키 확인 Ctrl + m, x
    - 선택된 여러 셀 병합 Ctrl + Shift + m
    - 현재 커서 위치에서 셀 분할 Ctrl + m, -
    - 주석 설정/해제 Ctrl + /

# 기본 자료형

## 기본 자료형에는 숫자형(정수(int), 실수(float)), 참/거짓(bool), 문자열(str) 등이 있음

In [1]:
1

1

In [2]:
type(1)

int

In [3]:
type(1.0)

float

### 자료형은 변환 가능: int(), float()

In [4]:
a = 1.5
b = int(a)
type(b)

int

In [5]:
b

1

In [6]:
False, True # 불리언 자료형

(False, True)

In [7]:
type(False)

bool

In [8]:
type('python') # 작은 따옴표

str

In [9]:
type("python") # 큰 따옴표

str

In [11]:
type('python'), type(.5)

(str, float)

In [12]:
a = 5
b = (a == 5) # equality operator
print(b)

True


In [13]:
a = 5
b = (a == 3)
c = 'KOR'
print(a, b, c)

5 False KOR


- 더하기

In [14]:
4 + 5

9

In [15]:
'KOR' + '15' # 문자열 더하기

'KOR15'

In [16]:
'KOR' + 15

TypeError: can only concatenate str (not "int") to str

In [17]:
'KOR' * 3

'KORKORKOR'

- 수는 수끼리, 문자열은 문자열끼리 더할 수 있음
- 자료형 변경은 str(), float(), int() 등을 이용

In [18]:
'KOR' + str(15)

'KOR15'

In [19]:
type(str(15))

str

In [20]:
float(str(15))

15.0

- bool 자료형에 사칙연산을 적용할 경우 False는 0, True는 1의 값을 갖는 것으로 처리됨

In [21]:
4 + True

5

In [22]:
4 + False

4

In [23]:
4 * True

4

In [24]:
4 * False

0

In [25]:
int(True), float(True)

(1, 1.0)

- 문자열 포맷: f-string, print(): 결과값 표시

In [26]:
a = 2
b = 'two'
print(a, b)

2 two


In [30]:
print(a)
print(b)

2
two


In [ ]:
a
b

'two'

In [ ]:
print(a)
print(b)

1.123445560498
two


In [31]:
print(f'{a} is {b}')

2 is two


In [32]:
a = 1.123445560498

In [33]:
print(f'{a:.5f} is {b}')

1.12345 is two


In [34]:
print(f'{a:.2f} is {b:}')

1.12 is two


In [35]:
print(f'{b} is {a:.2f}')

two is 1.12


In [36]:
print(f'{b} is not {10000:,}') # 천단위로 , 찍기

two is not 10,000


In [37]:
print(f'{b} is not {10000:,.2f}')

two is not 10,000.00


In [40]:
print(f'{1000000:,.2f}')

1,000,000.00


- 문자열에서 공백 없애기: strip(), lstrip(), rstrip()

In [41]:
" abc  "

' abc  '

In [42]:
" abc ".lstrip()

'abc '

In [43]:
" abc ".rstrip()

' abc'

In [44]:
" abc ".strip()

'abc'

In [ ]:
'abc'.strip()

'abc'

In [45]:
"abc".strip('bc')

'a'

In [46]:
"abc".strip('cd')

'ab'

# 기본 자료형 외 자주 사용되는 자료형: 리스트(list), 딕셔너리(dict), 튜플(tuple)
## 리스트
- 대괄호 [ ]로 표현하며 시퀀스 형태로 입력

In [47]:
a = [1, 2, 3]

In [58]:
a = [1, 2, 3]
b = ['one', 'two', 'three']
c = [1, 'one', True]
c

[1, 'one', True]

In [49]:
type(a), type(b)

(list, list)

In [52]:
# 인덱싱: a[], 0부터 시작, 마지막은 n-1 또는 -1, 여러 항목은 a[0:2] 또는 a[:2]
a1 = a[0:2]
a1

[1, 2]

In [53]:
a * 2 # matlab과 같은 결과를 얻으려면 list comprehension 또는 numpy 라이브러리 필요

[1, 2, 3, 1, 2, 3]

In [54]:
import numpy as np
numpy.function()

In [55]:
import numpy as np
a = np.array([1, 2, 3])
a * 2

array([2, 4, 6])

In [56]:
b * 3

['one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three']

In [59]:
a + b

[1, 2, 3, 'one', 'two', 'three']

In [60]:
a + 5

TypeError: can only concatenate list (not "int") to list

In [61]:
a + 'four'

TypeError: can only concatenate list (not "str") to list

- list에 숫자 또는 문자열을 더하는 연산이 정의되어 있지 않으므로 오류발생

In [62]:
a + [5]

[1, 2, 3, 5]

In [63]:
b + ['four']

['one', 'two', 'three', 'four']

In [64]:
b.append('four')
print(b)

['one', 'two', 'three', 'four']


- list comprehension: 각 항목에 어떤 연산을 해서 새로운 리스트 생성

In [65]:
a

[1, 2, 3]

In [66]:
[i + 2 for i in a]

[3, 4, 5]

In [67]:
# for loop
d = []
for i in a:
  d.append(i + 2)
d

[3, 4, 5]

In [68]:
# numpy
import numpy as np
aa = np.array(a)
list(aa + 2)

[3, 4, 5]

- 리스트에 있는 문자열을 특정 기호로 연결

In [69]:
b

['one', 'two', 'three', 'four']

In [70]:
':'.join(b)

'one:two:three:four'

- 파이썬 인덱스는 0부터 시작하는 것에 유의

In [71]:
a

[1, 2, 3]

In [73]:
a[0:2] # [포함:미포함]

[1, 2]

In [75]:
a[0:-1] # 첫번째 인덱스는 포함, 두번째 인덱스는 미포함

[1, 2]

- list의 마지막 항목의 인덱스는 -1

In [76]:
a[-1]

3

In [77]:
a = ['KOR', 'USA', 'CHN']
print(a[0])
print(a[-1])
print(a[0:2])
print(a[-2:])
#print(a[0], a[-1], a[:2], a[-2:])

KOR
CHN
['KOR', 'USA']
['USA', 'CHN']


- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [78]:
a

['KOR', 'USA', 'CHN']

In [79]:
a * 4

['KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN']

In [80]:
print(a * 4)

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']


In [81]:
from pprint import pprint

In [82]:
%pprint # % 매직명령어

Pretty printing has been turned OFF


In [83]:
a * 4

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']

- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- print()가 출력하는 각 항목 사이를 구분하기 위해 sep = '기호'를 지정
- print()가 마지막에 출력할 내용을 지정하기 위해 end = '기호'를 지정(기본은 '\n')

In [84]:
print(a)

['KOR', 'USA', 'CHN']


In [85]:
print(*a)

KOR USA CHN


In [86]:
print(*a, sep = ', ')

KOR, USA, CHN


In [87]:
print(*a, sep = ',')

KOR,USA,CHN


In [88]:
print(*a, sep = ', ', end = '.')

KOR, USA, CHN.

- list comprehension: for-loop 구문 한줄로 간단하게 표현하는 방법

In [89]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS'] # output이 KOR, USA가 되도록

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [90]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN', 'AUS']]

['KOR', 'USA']

In [91]:
d=[]
for s in ['KOR', 'USA', 'CHN']:
  if s not in ['CHN', 'AUS']:
    d.append(s)
d

['KOR', 'USA']

- set() 이용

In [92]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

({'CHN', 'USA', 'KOR'}, {'AUS', 'CHN'})

In [93]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

['USA', 'KOR']

- 문자열 리스트 항목별로 문자열 더하기

In [94]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

['KOR:g', 'USA:g', 'CHN:g']

In [ ]:
# 리스트 컴프리헨션으로 ['KO', 'US', 'CH']로 출력되게


In [ ]:
# 리스트 컴프리헨션으로 ['KO', 'USA', 'CHN']으로 출력되게


- 문자열은 각 캐릭터(123.../abc.../가나다... 등)로 구성된 리스트로 취급

In [ ]:
[1, 2, 3]

In [95]:
a = 'abcde'
a

'abcde'

In [96]:
a[:3]

'abc'

In [97]:
a[-2:]

'de'

In [98]:
"가나다라마"[0:2]

'가나'

- 이전 실행한 출력셀의 값 불러오기

In [99]:
_

'가나'

In [100]:
Out[59]

[1, 2, 3, 'one', 'two', 'three']

In [ ]:
_

'de'

- range()로 수 리스트 만들기
    - range(s, e, i): 처음 위치(생략시 0), 마지막 위치(리스트에 포함 안됨), 수 간격(생략시 1)
    - for-loop 등에서 주로 이용하며, 순서대로 해당하는 값만 필요하므로 실제 리스트를 생성하지 않음
        - 리스트 생성시 메모리 공간을 크게 차지할 수 있으므로 비효율적임
    - 리스트를 생성하기 위해서는 list() 함수 실행

In [101]:
list(range(1, 10, 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
for i in range(5):  # range(0, 5, 1)와 동일
    print(i)

0
1
2
3
4


In [103]:
for i in range(5, 0, -2):
    print(i)

5
3
1


In [104]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 딕셔너리 자료형: key와 value로 구성된 집합, { }로 표현

In [ ]:
{'key1': value1, 'key2': value2}

In [105]:
[1, 2, 3]

[1, 2, 3]

In [106]:
dic = {'a': 1, 'b': 2}

In [107]:
dic['a']

1

In [108]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [109]:
iso['US']

'USA'

In [110]:
iso['KR']

'KOR'

In [111]:
iso.keys() # 키값 출력

dict_keys(['US', 'KR', 'JP', 'CN'])

In [112]:
iso.values()

dict_values(['USA', 'KOR', 'JPN', 'CHN'])

In [113]:
iso['AU'] = 'AUS' # 딕셔너리에 추가

In [114]:
iso

{'US': 'USA', 'KR': 'KOR', 'JP': 'JPN', 'CN': 'CHN', 'AU': 'AUS'}

- dict, zip으로 딕셔너리 만들기

In [ ]:
zip([1, 2, 3], [a, b, c])

In [115]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

- key 이름 바꾸기: 딕셔너리 컴프리헨션

In [116]:
{f'new_{key}':x for key, x in dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP'])).items()}

{'new_한국': 'KR', 'new_미국': 'US', 'new_일본': 'JP'}

In [117]:
import pandas as pd
countries = pd.DataFrame(['South Korea', 'United States', 'North Korea'])
print(countries)

               0
0    South Korea
1  United States
2    North Korea


In [118]:
cdict = {'South Korea':'KR', 'United States':'US', 'Japan':'JP'}
countries.replace(cdict)

0
0           KR
1           US
2  North Korea

### 튜플: 리스트와 유사하나 값이 불변하는 특성을 가짐, ( )로 표현

In [119]:
a = (1, 2, 3)

In [120]:
a[0] = 2

TypeError: 'tuple' object does not support item assignment

In [121]:
my_tuple = (1, 2, 'hello', [1, 2, 3])
print(my_tuple[0])
my_tuple[0] = 3

1


TypeError: 'tuple' object does not support item assignment

In [122]:
my_list = [1 ,2 ,3 ,4, 5]
my_list[0] = 2
my_list

[2, 2, 3, 4, 5]

In [123]:
a = 5, 10

In [124]:
type(a)

<class 'tuple'>

In [125]:
print(a)

(5, 10)


In [126]:
a, b, c = 5, 10, 15
print(a, b, c)

5 10 15


In [127]:
a, b = b, a
print(a, b)

10 5


In [ ]:
c = 1, 2, 3
print(type(c))

<class 'tuple'>


In [ ]:
c

(1, 2, 3)

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
import numpy as np
from numpy import array

array([1,2,3])

array([1, 2, 3])

### method

In [128]:
a = ['123', '2ab', '3']

In [130]:
dir(a[0])

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [131]:
a[0].isnumeric()

True

In [132]:
a[1].isnumeric()

False

In [135]:
a = a[0].replace(a[0], '4')

In [136]:
a

'4'

## 연습문제

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열로 구성된 리스트를 생성 (힌트: 리스트 컴프리헨션, f-string)
- 아래 리스트와 인덱스를 이용하여 일본과 중국을 제외한 국가에 대해서만 국가명_연도 문자열 리스트를 생성

In [ ]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자를 나타내는 문자열만 선택하여 리스트를 생성하라(힌트, isnumeric() 또는 isdigit(), strip() method 이용)

In [ ]:
strings = ['KOR', '한국', ' 15', "True", '1000']

# 문법

- 파이썬에서 for loop, if 구문, 함수 정의시 indentation(스페이스 4개) 이용
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐


```
<C>
if (i=1; i<=n; i++) {
  printf("%d\n", i);
}

<matlab>
for i = 1:n
    disp(i)
end

<python>
for i = range(1, n+1):
    disp(i)
```

## definition: 함수

In [ ]:
def sum_two_numbers(a, b):
    return a + b

In [ ]:
sum_two_numbers(1, 2)

3

In [ ]:
def sum_three_numbers(a, b, c=4):
    return a + b + c

In [ ]:
sum_three_numbers(1, 2, 0)

3

In [ ]:
sum_three_numbers(1, 2)

7

In [ ]:
sum_three_numbers(b=1, a=4) # 순서 바꾸기

9

- labmda x: 표현식

In [ ]:
sum_two_numbers2 = lambda x, y: x + y # lambda 함수: 간단한 한줄짜리 함수

In [ ]:
sum_two_numbers2(1, 2)

3

## for-loop, if-else 구문

In [ ]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

KOR is my country.
USA
CHN


## enumerate: 반복 가능한 하나의 객체의 인덱스와 값 추출

In [ ]:
for index, c in enumerate(countries):
    print(index, c)

0 KOR
1 USA
2 CHN


## zip: 반복가능한 객체가 2개 이상인 경우, 각 객체의 요소를 순서대로 추출

In [ ]:
for i, c in zip(countries, ['한국', '미국', '중국']):
    print(i, c)

KOR 한국
USA 미국
CHN 중국


## continue, break, pass

In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        continue
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2
3 is not 2


In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        break
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2


In [ ]:
A = True

if A:
    print('True')
else:
    print('False')

True


In [ ]:
if A:
    pass
else:
    print('False')

## list comprehension v. for-loop
- 앞 리스트에서 뒤 리스트에 속한 항목 제외하기

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

['KOR', 'USA']

In [ ]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

['KOR', 'USA']

# 라이브러리
- Numpy: 매틀랩 대체, 과학적 연산
- Pandas: 데이터 분석
- Matplotlib: 데이터 시각화, 그래프
- os, pickle: 운영체제, 시스템과 상호작용
- Statsmodels: 통계분석
- Scikit-learn, TensorFlow: 머신러닝, AI

## numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [ ]:
import numpy # numpy 라이브러리 함수를 사용하려면 numpy. 으로 표현
import numpy as np # numpy. 에서 np. 으로 대체
print(numpy.sin(0), np.sin(0))

0.0 0.0


In [ ]:
print(sin(0)) # np. 로 시작하지 않기 때문에 오류

NameError: name 'sin' is not defined

In [ ]:
print(np.pi)

3.141592653589793


## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [ ]:
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [ ]:
type(a1)

<class 'numpy.ndarray'>

In [ ]:
print(a1.ndim)

2


In [ ]:
print(a1.shape)

(3, 3)


In [ ]:
a1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [ ]:
a1[:2, :2]

array([[1, 2],
       [2, 3]])

In [ ]:
a1[:, 0]

array([1, 2, 4])

In [ ]:
a1[0, :]

array([1, 2, 3])

## 통계량 및 연산

In [ ]:
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [ ]:
print(v.ndim)

1


In [ ]:
print(v.shape)

(3,)


In [ ]:
v.mean()

2.0

In [ ]:
v.std()

0.816496580927726

In [ ]:
v.min()

1

In [ ]:
print(v.mean(), v.std(), v.max())

2.0 0.816496580927726 3


In [ ]:
np.sin([0, np.pi / 2, np.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0] = -1

In [ ]:
a

array([[-1,  2],
       [ 3,  4]])

In [ ]:
a[0] = 0
a

array([[0, 0],
       [3, 4]])

In [ ]:
a[:, 1] = [5, 6]
a

array([[0, 5],
       [3, 6]])

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [ ]:
v1 + 1

array([2, 3, 4])

In [ ]:
v1 * 2

array([2, 4, 6])

In [ ]:
v1 ** 2 #제곱

array([1, 4, 9])

In [ ]:
v1 + v2

array([0, 2, 4])

In [ ]:
np.log(v1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(v1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [ ]:
a2 = np.array([[1, 2], [3, 4], [5, 6]])
a3 = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
a2.shape

(3, 2)

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1 * a2 # 행렬 연산 아님, 원소별 곱이기 때문에 shape이 같아야함

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
a2 * a3

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [ ]:
print(a1)
print(a2)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a1.dot(a2)

array([[22, 28],
       [31, 40]])

In [ ]:
np.dot(a1, a2)

array([[22, 28],
       [31, 40]])

In [ ]:
np.dot(a2, a1)

array([[ 5,  8, 11],
       [11, 18, 25],
       [17, 28, 39]])

In [ ]:
a1 @ a2 # 파이썬 3.5 이상

array([[22, 28],
       [31, 40]])

In [ ]:
A = np.dot(a1, a2)
print(A)

[[22 28]
 [31 40]]


- 역행렬: numpy.linalg.inv() 함수 이용, linalg는 numpy라이브러리의 선형대수 연산을 위한 서브모듈

In [ ]:
np.linalg.inv(a1.dot(a2))

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [ ]:
from numpy.linalg import inv

In [ ]:
inv(a1.dot(a2))

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [ ]:
inv(a1 @ a2)

array([[ 3.33333333, -2.33333333],
       [-2.58333333,  1.83333333]])

In [ ]:
a1.shape[0]

2

In [ ]:
np.identity(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(a1.shape[0], dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
from numpy import identity as eye #eye()

In [ ]:
eye(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

- 레온티에프 역행렬: $(I - A)^{-1}$

In [ ]:
A

array([[22, 28],
       [31, 40]])

In [ ]:
np.linalg.inv(np.identity(A.shape[0]) - A)

array([[ 0.79591837, -0.57142857],
       [-0.63265306,  0.42857143]])

In [ ]:
inv(eye(A.shape[0]) - A)

array([[ 0.79591837, -0.57142857],
       [-0.63265306,  0.42857143]])

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [ ]:
# np.random.randn(n)

In [ ]:
import numpy as np

In [ ]:
numpy.random.seed(1)
rsn = np.random.randn(10) # 표준정규분포에서 샘플링
print(rsn)
print(rsn.ndim)
print(rsn.shape)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]
1
(10,)


In [ ]:
numpy.random.seed(1)
rsn = np.random.randn(10,10) # 표준정규분포에서 샘플링
print(rsn)
print(rsn.ndim)
print(rsn.shape)

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127
  -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595 -0.68372786
  -0.12289023 -0.93576943 -0.26788808  0.53035547]
 [-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613 -0.0126646
  -1.11731035  0.2344157   1.65980218  0.74204416]
 [-0.19183555 -0.88762896 -0.74715829  1.6924546   0.05080775 -0.63699565
   0.19091548  2.10025514  0.12015895  0.61720311]
 [ 0.30017032 -0.35224985 -1.1425182  -0.34934272 -0.20889423  0.58662319
   0.83898341  0.93110208  0.28558733  0.88514116]
 [-0.75439794  1.25286816  0.51292982 -0.29809284  0.48851815 -0.07557171
   1.13162939  1.51981682  2.18557541 -1.39649634]
 [-1.44411381 -0.50446586  0.16003707  0.87616892  0.31563495 -2.02220122
  -0.30620401  0.82797464  0.23009474  0.76201118]
 [

In [ ]:
numpy.random.seed(1)
rsn1 = np.random.normal(2, 5, 10) # 평균이 2, 분산이 25인 정규분포
print(rsn1)

[10.12172682 -1.05878207 -0.64085876 -3.36484311  6.32703815 -9.50769348
 10.72405882 -1.8060345   3.59519548  0.75314812]


In [ ]:
numpy.random.seed(1)
rsn1 = np.random.normal(2, 5, 10000) # 평균이 2, 분산이 25인 정규분포
print(rsn1.mean())
print(rsn1.var())
print(rsn1.std())

2.048863283495525
24.93932903879117
4.993929218440242


In [ ]:
np.random.seed(1)
rsi = np.random.randint(1, 10, 10) # 1과 9사이에서 10개 샘플링

In [ ]:
rsi

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5])

In [ ]:
rsu = np.random.uniform(-1, 1, 10)

In [ ]:
rsu

array([-0.16161097,  0.370439  , -0.5910955 ,  0.75623487, -0.94522481,
        0.34093502, -0.1653904 ,  0.11737966, -0.71922612, -0.60379702])

# 연습문제
1. $x + y + x*y + x^2$ 계산해서 return하는 함수 생성 (def)

2. 아래 a1, a2 리스트를 이용해서 a1의 요소가 key이고, a2의 요소가 value인 딕셔너리 생성( dict(), zip() )

In [ ]:
a1 = ['a', 'b', 'c', 'd', 'e']
a2 = list(range(5))

3. 리스트 컴프리헨션을 이용해서 아래 a 리스트의 각 요소를 세제곱한 리스트 생성

In [ ]:
a = list(range(2, 10))

4. 위의 a 리스트를 ndarray 자료형으로 변환하고 제곱하시오

5. 2의 a1 리스트의 인덱스와 요소를 반복구문을 통해 print하시오 ( enumerate() )